telegram:
  token: 1769040448:AAFrRtJgI6Y4HSWExg58EQtdgBocvOJGDdo  # Telegram bot tokens look like this: 113031530:AAH_4c5Gt9gsVu82OVNjUV7poU7PodYiNsA
  useFirstNameInsteadOfUsername: true
  colonAfterSenderName: true
  skipOldMessages: true
  sendEmojiWithStickers: true
discord:
  useNickname: false
  token: ODI4ODM0MjU3NTc2NTI1ODQ1.YGvWDg.kyon-_Xcc-D7KBPd2bDOTaJ6j_g       # Discord bot tokens look like this: MjI3MDA1NzIvOBQ2MzAzMiMz.DRf-aw.N0MVYtDxXYPSQew4g2TPqvQve2c
  skipOldMessages: true
  replyLength: 100
  maxReplyLines: 2
bridges:
  - name: Global chat Bridge1
    direction: both
    telegram:
      chatId: -1001205045316 # Remember that Telegram group and channel IDs are negative. Include the `-` if you are bridging a group or a channel
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      relayCommands: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '828853283653025802'       # This ID must be wrapped in single quotes. Example: '244791815503347712'
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      crossDeleteOnTelegram: true
debug: false
